# K Nearest Neighbor

###  Load in dependencies

In [5]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

###  Euclidean Distance

In [50]:
def euclidean(array1,array2,b1,b2):
    arrayjarak = []
    for i in range(len(array1)):
        jarak = np.round(((array1[i]-b1)**2)+((array2[i]-b2)**2))
        arrayjarak.append(jarak)
    return arrayjarak

###  K Nearset Neighbour

In [91]:
def knearest(array1,array2,array3,b1,b2):
    traindata = []
    arrayjarak = euclidean(array1,array2,b1,b2)
    traindata.append(array1)
    traindata.append(array2)
    traindata.append(array3)
    traindata.append(arrayjarak)
    return traindata

In [92]:
dayaTahanAsam = [8,4,4,7,5,6]
kekuatan = [4,5,6,7,6,5]
klasifikasi = ["Bagus", "Tidak Bagus", "Tidak Bagus", "Bagus", "Tidak Bagus", "Bagus"]

In [93]:
knearest(dayaTahanAsam,kekuatan,klasifikasi,7,4)

[[8, 4, 4, 7, 5, 6],
 [4, 5, 6, 7, 6, 5],
 ['Bagus', 'Tidak Bagus', 'Tidak Bagus', 'Bagus', 'Tidak Bagus', 'Bagus'],
 [1, 10, 13, 9, 8, 2]]

In [94]:
traindata = knearest(dayaTahanAsam,kekuatan,klasifikasi,7,4)
df = pd.DataFrame({"Daya Tahan Terhadap Asam (detik)":traindata[0], "Kekuatan (kg/m2)":traindata[1],"Class":traindata[2],"Jarak ke data uji (X1=7,X2=4)":traindata[3]})
result = df.sort_values(by=['Jarak ke data uji (X1=7,X2=4)'])
result

Daya Tahan Terhadap Asam (detik)  Kekuatan (kg/m2)        Class  \
0                                 8                 4        Bagus   
5                                 6                 5        Bagus   
4                                 5                 6  Tidak Bagus   
3                                 7                 7        Bagus   
1                                 4                 5  Tidak Bagus   
2                                 4                 6  Tidak Bagus   

   Jarak ke data uji (X1=7,X2=4)  
0                              1  
5                              2  
4                              8  
3                              9  
1                             10  
2                             13

In [95]:
result['Class'].head(3).values

array(['Bagus', 'Bagus', 'Tidak Bagus'], dtype=object)

## Iris Flower Dataset 

In [96]:
irisDf = pd.read_csv("./data/iris.csv")
irisDf

sepal length in cm  sepal width in cm  petal length in cm  \
0                   5.1                3.5                 1.4   
1                   4.9                3.0                 1.4   
2                   4.7                3.2                 1.3   
3                   4.6                3.1                 1.5   
4                   5.0                3.6                 1.4   
..                  ...                ...                 ...   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4                 5.4   
149                 5.9                3.0                 5.1   

     petal width in cm           class  
0                  0.2     Iris-setosa  
1                  0.2     Iris-setosa  
2                  0.2     Iris-setosa  
3                  0.2     Iris-setosa  
4                  0.2     Iris-setosa  
..                 ...             ...  
145                2.3  Iris-virginica  
146                1.9  Iris-virginica  
147                2.0  Iris-virginica  
148                2.3  Iris-virginica  
149                1.8  Iris-virginica  

[150 rows x 5 columns]

### Feature Selection

In [97]:
irisData = pd.DataFrame({'Sepal Length': irisDf['sepal length in cm'], 
                         'Sepal Width': irisDf['sepal width in cm'], 
                         'Class': irisDf['class']})
irisData

Sepal Length  Sepal Width           Class
0             5.1          3.5     Iris-setosa
1             4.9          3.0     Iris-setosa
2             4.7          3.2     Iris-setosa
3             4.6          3.1     Iris-setosa
4             5.0          3.6     Iris-setosa
..            ...          ...             ...
145           6.7          3.0  Iris-virginica
146           6.3          2.5  Iris-virginica
147           6.5          3.0  Iris-virginica
148           6.2          3.4  Iris-virginica
149           5.9          3.0  Iris-virginica

[150 rows x 3 columns]

In [98]:
sepalLength = irisData['Sepal Length'].values
sepalLength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [99]:
sepalWidth = irisData['Sepal Width'].values
sepalWidth

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 2.6, 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3.1, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. ])

In [100]:
sepalClass = irisData['Class'].values
sepalClass

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [101]:
knearest(sepalLength,sepalWidth,sepalClass,3,2)

[array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9]),
 array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
      

In [102]:
traindata = knearest(sepalLength,sepalWidth,sepalClass,3,2)
df = pd.DataFrame({"Sepal Length":traindata[0], 
                   "Sepal Width":traindata[1],
                   "Class":traindata[2],
                   "Jarak ke data uji (X1=7,X2=4)":traindata[3]})
result = df.sort_values(by=['Jarak ke data uji (X1=7,X2=4)'])
result

Sepal Length  Sepal Width           Class  Jarak ke data uji (X1=7,X2=4)
41            4.5          2.3     Iris-setosa                            2.0
42            4.4          3.2     Iris-setosa                            3.0
38            4.4          3.0     Iris-setosa                            3.0
8             4.4          2.9     Iris-setosa                            3.0
13            4.3          3.0     Iris-setosa                            3.0
..            ...          ...             ...                            ...
105           7.6          3.0  Iris-virginica                           22.0
122           7.7          2.8  Iris-virginica                           23.0
135           7.7          3.0  Iris-virginica                           23.0
117           7.7          3.8  Iris-virginica                           25.0
131           7.9          3.8  Iris-virginica                           27.0

[150 rows x 4 columns]

In [103]:
result['Class'].head(3).values

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [104]:
mallCustomersDf = pd.read_csv("https://raw.githubusercontent.com/pavankalyan1997/Machine-learning-without-any-libraries/master/2.Clustering/1.K_Means_Clustering/Mall_Customers.csv")
mallCustomersDf.head(10)

CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40
5           6  Female   22                  17                      76
6           7  Female   35                  18                       6
7           8  Female   23                  18                      94
8           9    Male   64                  19                       3
9          10  Female   30                  19                      72

In [105]:
genre = mallCustomersDf['Genre'].values
genre

array(['Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female',
       'Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Female',
       'Male', 'Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female',
       'Female', 'Male', 'Female', 'Male', 'Male', 'Female', 'Female',
       'Female', 'Female', 'Female', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Female', 'Female', 'Female', 'Female', 'Female',
       'Female', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male',
       'Female', 'Male', 'Female', 'Male', 'Male', 'Male', 'Female',
       'Female', 'Male', 'Male', 'Female', 'Female', 'Male', 'Female',
       'Male', 'Female', 'Female', 'Female', 'Male', 'Male', 'Female',
       'Male', 'Female', 'Female', 'Male', 'Male', 'Male', 'Female',
       'Female', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female',
       'Male', 'Male', 'Female', 'Female', 'Male', 'Female', 'Female',


In [106]:
income = mallCustomersDf['Annual Income (k$)'].values
income

array([ 15,  15,  16,  16,  17,  17,  18,  18,  19,  19,  19,  19,  20,
        20,  20,  20,  21,  21,  23,  23,  24,  24,  25,  25,  28,  28,
        28,  28,  29,  29,  30,  30,  33,  33,  33,  33,  34,  34,  37,
        37,  38,  38,  39,  39,  39,  39,  40,  40,  40,  40,  42,  42,
        43,  43,  43,  43,  44,  44,  46,  46,  46,  46,  47,  47,  48,
        48,  48,  48,  48,  48,  49,  49,  50,  50,  54,  54,  54,  54,
        54,  54,  54,  54,  54,  54,  54,  54,  57,  57,  58,  58,  59,
        59,  60,  60,  60,  60,  60,  60,  61,  61,  62,  62,  62,  62,
        62,  62,  63,  63,  63,  63,  63,  63,  64,  64,  65,  65,  65,
        65,  67,  67,  67,  67,  69,  69,  70,  70,  71,  71,  71,  71,
        71,  71,  72,  72,  73,  73,  73,  73,  74,  74,  75,  75,  76,
        76,  77,  77,  77,  77,  78,  78,  78,  78,  78,  78,  78,  78,
        78,  78,  78,  78,  79,  79,  81,  81,  85,  85,  86,  86,  87,
        87,  87,  87,  87,  87,  88,  88,  88,  88,  93,  93,  9

In [107]:
spending = mallCustomersDf['Spending Score (1-100)'].values
spending

array([39, 81,  6, 77, 40, 76,  6, 94,  3, 72, 14, 99, 15, 77, 13, 79, 35,
       66, 29, 98, 35, 73,  5, 73, 14, 82, 32, 61, 31, 87,  4, 73,  4, 92,
       14, 81, 17, 73, 26, 75, 35, 92, 36, 61, 28, 65, 55, 47, 42, 42, 52,
       60, 54, 60, 45, 41, 50, 46, 51, 46, 56, 55, 52, 59, 51, 59, 50, 48,
       59, 47, 55, 42, 49, 56, 47, 54, 53, 48, 52, 42, 51, 55, 41, 44, 57,
       46, 58, 55, 60, 46, 55, 41, 49, 40, 42, 52, 47, 50, 42, 49, 41, 48,
       59, 55, 56, 42, 50, 46, 43, 48, 52, 54, 42, 46, 48, 50, 43, 59, 43,
       57, 56, 40, 58, 91, 29, 77, 35, 95, 11, 75,  9, 75, 34, 71,  5, 88,
        7, 73, 10, 72,  5, 93, 40, 87, 12, 97, 36, 74, 22, 90, 17, 88, 20,
       76, 16, 89,  1, 78,  1, 73, 35, 83,  5, 93, 26, 75, 20, 95, 27, 63,
       13, 75, 10, 92, 13, 86, 15, 69, 14, 90, 32, 86, 15, 88, 39, 97, 24,
       68, 17, 85, 23, 69,  8, 91, 16, 79, 28, 74, 18, 83], dtype=int64)

In [129]:
traindata = knearest(income,spending,genre,18,94)
df = pd.DataFrame({"Annual Income":traindata[0], 
                   "Spending Score(1-100)":traindata[1],
                   "Genre":traindata[2],
                   "Jarak ke data uji (X1=17,X2=25)":traindata[3]})
# result = df.head(10).sort_values(by=['Jarak ke data uji (X1=17,X2=25)'])
df.head(10)

Annual Income  Spending Score(1-100)   Genre  \
0             15                     39    Male   
1             15                     81    Male   
2             16                      6  Female   
3             16                     77  Female   
4             17                     40  Female   
5             17                     76  Female   
6             18                      6  Female   
7             18                     94  Female   
8             19                      3    Male   
9             19                     72  Female   

   Jarak ke data uji (X1=17,X2=25)  
0                             3034  
1                              178  
2                             7748  
3                              293  
4                             2917  
5                              325  
6                             7744  
7                                0  
8                             8282  
9                              485

In [120]:
result['Class'].head(5).values

array(['Male', 'Female', 'Female', 'Female', 'Male'], dtype=object)

In [125]:
result

Annual Income  Spending Score(1-100)   Genre  \
0             15                     39    Male   
4             17                     40  Female   
2             16                      6  Female   
6             18                      6  Female   
8             19                      3    Male   
9             19                     72  Female   
5             17                     76  Female   
3             16                     77  Female   
1             15                     81    Male   
7             18                     94  Female   

   Jarak ke data uji (X1=17,X2=25)  
0                              200  
4                              225  
2                              362  
6                              362  
8                              488  
9                             2213  
5                             2601  
3                             2705  
1                             3140  
7                             4762