# K Nearest Neighbor

###  Load in dependencies

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

###  Euclidean Distance

In [2]:
def euclidean(array1,array2,b1,b2):
    arrayjarak = []
    for i in range(len(array1)):
        jarak = int(np.round(np.square(np.sqrt((array1[i]-b1)**2+(array2[i]-b2)**2))))
        arrayjarak.append(jarak)
    return arrayjarak

###  K Nearset Neighbour

In [3]:
def knearest(array1,array2,array3,b1,b2):
    traindata = []
    arrayjarak = euclidean(array1,array2,7,4)
    traindata.append(array1)
    traindata.append(array2)
    traindata.append(array3)
    traindata.append(arrayjarak)
    return traindata

In [4]:
dayaTahanAsam = [8,4,4,7,5,6]
kekuatan = [4,5,6,7,6,5]
klasifikasi = ["Bagus", "Tidak Bagus", "Tidak Bagus", "Bagus", "Tidak Bagus", "Bagus"]

In [5]:
knearest(dayaTahanAsam,kekuatan,klasifikasi,7,4)

[[8, 4, 4, 7, 5, 6],
 [4, 5, 6, 7, 6, 5],
 ['Bagus', 'Tidak Bagus', 'Tidak Bagus', 'Bagus', 'Tidak Bagus', 'Bagus'],
 [1, 10, 13, 9, 8, 2]]

In [6]:
traindata = knearest(dayaTahanAsam,kekuatan,klasifikasi,7,4)
df = pd.DataFrame({"Daya Tahan Terhadap Asam (detik)":traindata[0], "Kekuatan (kg/m2)":traindata[1],"Class":traindata[2],"Jarak ke data uji (X1=7,X2=4)":traindata[3]})
df.sort_values(by='Jarak ke data uji (X1=7,X2=4)')
df

Daya Tahan Terhadap Asam (detik)  Kekuatan (kg/m2)        Class  \
0                                 8                 4        Bagus   
1                                 4                 5  Tidak Bagus   
2                                 4                 6  Tidak Bagus   
3                                 7                 7        Bagus   
4                                 5                 6  Tidak Bagus   
5                                 6                 5        Bagus   

   Jarak ke data uji (X1=7,X2=4)  
0                              1  
1                             10  
2                             13  
3                              9  
4                              8  
5                              2

In [7]:
df['Class'].head(3).values

array(['Bagus', 'Tidak Bagus', 'Tidak Bagus'], dtype=object)

## Iris Flower Dataset 

In [10]:
irisDf = pd.read_csv("./data/iris.csv")
irisDf

sepal length in cm  sepal width in cm  petal length in cm  \
0                   5.1                3.5                 1.4   
1                   4.9                3.0                 1.4   
2                   4.7                3.2                 1.3   
3                   4.6                3.1                 1.5   
4                   5.0                3.6                 1.4   
..                  ...                ...                 ...   
145                 6.7                3.0                 5.2   
146                 6.3                2.5                 5.0   
147                 6.5                3.0                 5.2   
148                 6.2                3.4                 5.4   
149                 5.9                3.0                 5.1   

     petal width in cm           class  
0                  0.2     Iris-setosa  
1                  0.2     Iris-setosa  
2                  0.2     Iris-setosa  
3                  0.2     Iris-setosa  
4                  0.2     Iris-setosa  
..                 ...             ...  
145                2.3  Iris-virginica  
146                1.9  Iris-virginica  
147                2.0  Iris-virginica  
148                2.3  Iris-virginica  
149                1.8  Iris-virginica  

[150 rows x 5 columns]

### Feature Selection

In [16]:
irisData = pd.DataFrame({'Sepal Length': irisDf['sepal length in cm'], 
                         'Sepal Width': irisDf['sepal width in cm'], 
                         'Class': irisDf['class']})
irisData

Sepal Length  Sepal Width           Class
0             5.1          3.5     Iris-setosa
1             4.9          3.0     Iris-setosa
2             4.7          3.2     Iris-setosa
3             4.6          3.1     Iris-setosa
4             5.0          3.6     Iris-setosa
..            ...          ...             ...
145           6.7          3.0  Iris-virginica
146           6.3          2.5  Iris-virginica
147           6.5          3.0  Iris-virginica
148           6.2          3.4  Iris-virginica
149           5.9          3.0  Iris-virginica

[150 rows x 3 columns]

In [19]:
sepalLength = irisData['Sepal Length'].values
sepalLength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [20]:
sepalWidth = irisData['Sepal Width'].values
sepalWidth

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 2.6, 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3.1, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. ])

In [23]:
sepalClass = irisData['Class'].values
sepalClass

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [24]:
knearest(sepalLength,sepalWidth,sepalClass,7,4)

[array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9]),
 array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
      

In [25]:
traindata = knearest(sepalLength,sepalWidth,sepalClass,7,4)
df = pd.DataFrame({"Sepal Length":traindata[0], "Sepal Width":traindata[1],"Class":traindata[2],"Jarak ke data uji (X1=7,X2=4)":traindata[3]})
df.sort_values(by='Jarak ke data uji (X1=7,X2=4)')
df

Sepal Length  Sepal Width           Class  Jarak ke data uji (X1=7,X2=4)
0             5.1          3.5     Iris-setosa                              4
1             4.9          3.0     Iris-setosa                              5
2             4.7          3.2     Iris-setosa                              6
3             4.6          3.1     Iris-setosa                              7
4             5.0          3.6     Iris-setosa                              4
..            ...          ...             ...                            ...
145           6.7          3.0  Iris-virginica                              1
146           6.3          2.5  Iris-virginica                              3
147           6.5          3.0  Iris-virginica                              1
148           6.2          3.4  Iris-virginica                              1
149           5.9          3.0  Iris-virginica                              2

[150 rows x 4 columns]

In [26]:
df['Class'].head(3).values

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa'], dtype=object)