## Load in dependencies 

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

### Sungai Cibeureum Dataset

In [42]:
sungaiDf = pd.read_csv("./data/data_sungaicibereum.csv")
sungaiDf.head()

LOCATION  DAY     DATE TIME_WIB  TDS_PPM  TEMP_RIVER_C  TEMP_AIR_C
0  Sungai Cibeureum  Sun  3/19/17    10:00       88            22          25
1  Sungai Cibeureum  Sun  3/19/17    12:00       97            22          30
2  Sungai Cibeureum  Sun  3/19/17    14:00       83            22          33
3  Sungai Cibeureum  Sun  3/19/17    16:00      100            22          27
4  Sungai Cibeureum  Sun   4/9/17    10:00      100            22          32

## Mean, Bubble Sort 

In [37]:
def bubble_sort(nums):
    swapped = True
    while swapped:
        swapped = False
        for i in range(len(nums) - 1):
            if nums[i] > nums[i + 1]:
                nums[i], nums[i + 1] = nums[i + 1], nums[i]
                swapped = True


# Discretization 

In [146]:
endapanDf = sungaiDf['TDS_PPM'].values

In [147]:
bubble_sort(endapanDf)
endapanDf

array([ 80,  80,  80,  80,  80,  80,  80,  80,  80,  81,  81,  81,  81,
        81,  81,  81,  81,  81,  81,  82,  82,  82,  82,  82,  82,  82,
        82,  82,  82,  82,  82,  83,  83,  83,  83,  83,  83,  83,  83,
        83,  83,  83,  83,  83,  83,  83,  83,  84,  84,  84,  84,  84,
        84,  84,  84,  84,  84,  84,  85,  85,  85,  85,  85,  85,  85,
        85,  86,  86,  86,  86,  86,  87,  87,  87,  87,  87,  88,  88,
        88,  88,  88,  88,  88,  88,  88,  88,  88,  88,  88,  88,  89,
        89,  89,  89,  89,  89,  90,  90,  90,  90,  90,  90,  90,  90,
        90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  91,
        91,  91,  91,  91,  91,  91,  91,  91,  91,  91,  91,  92,  92,
        92,  92,  92,  92,  92,  93,  93,  93,  93,  93,  93,  93,  93,
        93,  93,  93,  93,  93,  93,  93,  93,  94,  94,  94,  94,  94,
        94,  94,  94,  94,  94,  94,  94,  94,  94,  94,  95,  95,  95,
        95,  95,  95,  95,  95,  95,  95,  95,  95,  95,  95,  9

In [148]:
tempRiverDf = sungaiDf['TEMP_RIVER_C'].values

In [149]:
bubble_sort(tempRiverDf)
tempRiverDf

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19,
       19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21

In [150]:
tempAirDf = sungaiDf['TEMP_AIR_C'].values

In [151]:
bubble_sort(tempAirDf)
tempAirDf

array([24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 27,
       28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29, 29,
       29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32,
       32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
       32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
       32, 32, 32, 32, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
       34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
       34, 34, 34, 34, 34

### Binning Mean

In [131]:
def binning_mean(arr,k):
    f = []
    n = 0
    for i in range(len(arr)):
        n = n + arr[i]
        if (i+1)%k == 0:
            r = n/k
            n = 0  
            for j in range(k):
                f.append(r)
    return f

In [142]:
dataEndapan = pd.DataFrame({'Endapan': endapanDf, 'Binning (Mean)':binning_mean(endapanDf,10)})
dataEndapan

Endapan  Binning (Mean)
0         80            80.1
1         80            80.1
2         80            80.1
3         80            80.1
4         80            80.1
..       ...             ...
375      124           123.9
376      124           123.9
377      125           123.9
378      125           123.9
379      125           123.9

[380 rows x 2 columns]

In [144]:
dataTempAir = pd.DataFrame({'Temperature Air': tempAirDf, 'Binning (Mean)':binning_mean(tempAirDf,10)})
dataTempAir

Temperature Air  Binning (Mean)
0                 24            24.0
1                 24            24.0
2                 24            24.0
3                 24            24.0
4                 24            24.0
..               ...             ...
375               41            41.0
376               41            41.0
377               41            41.0
378               41            41.0
379               41            41.0

[380 rows x 2 columns]

In [145]:
dataTempRiver = pd.DataFrame({'Temperature River': tempRiverDf, 'Binning (Mean)':binning_mean(tempRiverDf,10)})
dataTempRiver

Temperature River  Binning (Mean)
0                   15            15.0
1                   15            15.0
2                   15            15.0
3                   15            15.0
4                   15            15.0
..                 ...             ...
375                 25            25.0
376                 25            25.0
377                 25            25.0
378                 25            25.0
379                 25            25.0

[380 rows x 2 columns]

In [158]:
dataSungaiDf = pd.DataFrame({'Binning TDS': binning_mean(endapanDf,10),
                             'Binning Temp Air':binning_mean(tempAirDf,10),
                             'Binning Temp River':binning_mean(tempRiverDf,10)
                            })
dataSungaiDf

Binning TDS  Binning Temp Air  Binning Temp River
0           80.1              24.0                15.0
1           80.1              24.0                15.0
2           80.1              24.0                15.0
3           80.1              24.0                15.0
4           80.1              24.0                15.0
..           ...               ...                 ...
375        123.9              41.0                25.0
376        123.9              41.0                25.0
377        123.9              41.0                25.0
378        123.9              41.0                25.0
379        123.9              41.0                25.0

[380 rows x 3 columns]

# Feature Extraction

In [213]:
def rerata(arr):
    return sum(arr)/len(arr)

###  Covarians

In [214]:
def cov(x,y):
    n = len(x)
    a = 0
    for i in range(n):
        a = a+((x[i]-rerata(x))*(y[i]-rerata(y)))
    return a/(n-1)

In [269]:
x = binning_mean(endapanDf,10)
y = binning_mean(tempAirDf,10)
z = binning_mean(tempRiverDf,10)
matrix_cov = np.mat([[cov(x,x),cov(x,y),cov(x,z)],[cov(y,x),cov(y,y),cov(y,z)],[cov(z,x),cov(z,y),cov(z,z)]])
matrix_cov

matrix([[132.39775031,  43.69433412,  25.99570893],
        [ 43.69433412,  15.6552701 ,   9.2781697 ],
        [ 25.99570893,   9.2781697 ,   5.60392307]])

###  Vektor Eigen dan Nilai Eigen 

In [270]:
nilai_eigen,vektor_eigen= np.linalg.eig(matrix_cov)
print(nilai_eigen)
print(vektor_eigen)

[1.52137050e+02 1.44222446e+00 7.76690343e-02]
[[ 0.93220786  0.36191438  0.0025486 ]
 [ 0.31102561 -0.79748955 -0.516985  ]
 [ 0.18507182 -0.48273016  0.85599066]]


### Sorting Nilai Eigen 

In [277]:
bubble_sort(nilai_eigen)
nilai_eigen.reshape(3,1)

array([[7.76690343e-02],
       [1.44222446e+00],
       [1.52137050e+02]])

### Transpose Matrix W dan M 

In [290]:
w = np.array(vektor_eigen)
matrixw = np.array([[w[0][0],w[0][1]],[w[1][0],w[1][1]],[w[2][0],w[2][1]]])
matrixw

array([[ 0.93220786,  0.36191438],
       [ 0.31102561, -0.79748955],
       [ 0.18507182, -0.48273016]])

In [293]:
wt = matrixw.transpose()
wt

array([[ 0.93220786,  0.31102561,  0.18507182],
       [ 0.36191438, -0.79748955, -0.48273016]])

In [295]:
mt = np.array([x,y,z])
mt

array([[ 80.1,  80.1,  80.1, ..., 123.9, 123.9, 123.9],
       [ 24. ,  24. ,  24. , ...,  41. ,  41. ,  41. ],
       [ 15. ,  15. ,  15. , ...,  25. ,  25. ,  25. ]])

### Perkalian Matrix W dan M 

In [349]:
perkalian_matrix = np.dot(wt,mt,out=None)
perkalian_matrix.transpose()

array([[ 8.49105414e+01,  2.60864001e+00],
       [ 8.49105414e+01,  2.60864001e+00],
       [ 8.49105414e+01,  2.60864001e+00],
       [ 8.49105414e+01,  2.60864001e+00],
       [ 8.49105414e+01,  2.60864001e+00],
       [ 8.49105414e+01,  2.60864001e+00],
       [ 8.49105414e+01,  2.60864001e+00],
       [ 8.49105414e+01,  2.60864001e+00],
       [ 8.49105414e+01,  2.60864001e+00],
       [ 8.49105414e+01,  2.60864001e+00],
       [ 8.62270318e+01,  1.97785455e+00],
       [ 8.62270318e+01,  1.97785455e+00],
       [ 8.62270318e+01,  1.97785455e+00],
       [ 8.62270318e+01,  1.97785455e+00],
       [ 8.62270318e+01,  1.97785455e+00],
       [ 8.62270318e+01,  1.97785455e+00],
       [ 8.62270318e+01,  1.97785455e+00],
       [ 8.62270318e+01,  1.97785455e+00],
       [ 8.62270318e+01,  1.97785455e+00],
       [ 8.62270318e+01,  1.97785455e+00],
       [ 8.73703609e+01,  1.52076681e+00],
       [ 8.73703609e+01,  1.52076681e+00],
       [ 8.73703609e+01,  1.52076681e+00],
       [ 8.

# Feature Selection

### Forrest Fire Dataset

In [350]:
forrestDf = pd.read_csv("./data/forestfires.csv")
forrestDf.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

### Seleksi Fitur (FFMC,DMC,DC,ISI,temp,RH,wind,rain,area) 

In [353]:
dataForrestFire = pd.DataFrame({'FFMC': forrestDf['FFMC'], 'DMC': forrestDf['DMC'], 
                                'DC': forrestDf['DC'], 'ISI': forrestDf['ISI'], 
                                'TEMPERATURE(C)': forrestDf['temp'], 'RH': forrestDf['RH'], 
                                'WINDSPEED(km/h)': forrestDf['wind'], 'RAIN(mm/m2)': forrestDf['rain'], 
                                'AREA(ha)': forrestDf['area']})
dataForrestFire

FFMC    DMC     DC   ISI  TEMPERATURE(C)  RH  WINDSPEED(km/h)  \
0    86.2   26.2   94.3   5.1             8.2  51              6.7   
1    90.6   35.4  669.1   6.7            18.0  33              0.9   
2    90.6   43.7  686.9   6.7            14.6  33              1.3   
3    91.7   33.3   77.5   9.0             8.3  97              4.0   
4    89.3   51.3  102.2   9.6            11.4  99              1.8   
..    ...    ...    ...   ...             ...  ..              ...   
512  81.6   56.7  665.6   1.9            27.8  32              2.7   
513  81.6   56.7  665.6   1.9            21.9  71              5.8   
514  81.6   56.7  665.6   1.9            21.2  70              6.7   
515  94.4  146.0  614.7  11.3            25.6  42              4.0   
516  79.5    3.0  106.7   1.1            11.8  31              4.5   

     RAIN(mm/m2)  AREA(ha)  
0            0.0      0.00  
1            0.0      0.00  
2            0.0      0.00  
3            0.2      0.00  
4            0.0      0.00  
..           ...       ...  
512          0.0      6.44  
513          0.0     54.29  
514          0.0     11.16  
515          0.0      0.00  
516          0.0      0.00  

[517 rows x 9 columns]