## Load in dependencies 

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

### Iris Flower Dataset

In [3]:
irisDf = pd.read_csv("./data/iris.csv")
irisDf.head()

sepal length in cm  sepal width in cm  petal length in cm  \
0                 5.1                3.5                 1.4   
1                 4.9                3.0                 1.4   
2                 4.7                3.2                 1.3   
3                 4.6                3.1                 1.5   
4                 5.0                3.6                 1.4   

   petal width in cm        class  
0                0.2  Iris-setosa  
1                0.2  Iris-setosa  
2                0.2  Iris-setosa  
3                0.2  Iris-setosa  
4                0.2  Iris-setosa

### Sungai Cibeureum Dataset

In [42]:
sungaiDf = pd.read_csv("./data/data_sungaicibereum.csv")
sungaiDf.head()

LOCATION  DAY     DATE TIME_WIB  TDS_PPM  TEMP_RIVER_C  TEMP_AIR_C
0  Sungai Cibeureum  Sun  3/19/17    10:00       88            22          25
1  Sungai Cibeureum  Sun  3/19/17    12:00       97            22          30
2  Sungai Cibeureum  Sun  3/19/17    14:00       83            22          33
3  Sungai Cibeureum  Sun  3/19/17    16:00      100            22          27
4  Sungai Cibeureum  Sun   4/9/17    10:00      100            22          32

## Mean, Bubble Sort 

In [37]:
def bubble_sort(nums):
    swapped = True
    while swapped:
        swapped = False
        for i in range(len(nums) - 1):
            if nums[i] > nums[i + 1]:
                nums[i], nums[i + 1] = nums[i + 1], nums[i]
                swapped = True


## Discretization 

In [146]:
endapanDf = sungaiDf['TDS_PPM'].values

In [147]:
bubble_sort(endapanDf)
endapanDf

array([ 80,  80,  80,  80,  80,  80,  80,  80,  80,  81,  81,  81,  81,
        81,  81,  81,  81,  81,  81,  82,  82,  82,  82,  82,  82,  82,
        82,  82,  82,  82,  82,  83,  83,  83,  83,  83,  83,  83,  83,
        83,  83,  83,  83,  83,  83,  83,  83,  84,  84,  84,  84,  84,
        84,  84,  84,  84,  84,  84,  85,  85,  85,  85,  85,  85,  85,
        85,  86,  86,  86,  86,  86,  87,  87,  87,  87,  87,  88,  88,
        88,  88,  88,  88,  88,  88,  88,  88,  88,  88,  88,  88,  89,
        89,  89,  89,  89,  89,  90,  90,  90,  90,  90,  90,  90,  90,
        90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  90,  91,
        91,  91,  91,  91,  91,  91,  91,  91,  91,  91,  91,  92,  92,
        92,  92,  92,  92,  92,  93,  93,  93,  93,  93,  93,  93,  93,
        93,  93,  93,  93,  93,  93,  93,  93,  94,  94,  94,  94,  94,
        94,  94,  94,  94,  94,  94,  94,  94,  94,  94,  95,  95,  95,
        95,  95,  95,  95,  95,  95,  95,  95,  95,  95,  95,  9

In [148]:
tempRiverDf = sungaiDf['TEMP_RIVER_C'].values

In [149]:
bubble_sort(tempRiverDf)
tempRiverDf

array([15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19,
       19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 21

In [150]:
tempAirDf = sungaiDf['TEMP_AIR_C'].values

In [151]:
bubble_sort(tempAirDf)
tempAirDf

array([24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 27,
       28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29, 29,
       29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31,
       31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32,
       32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
       32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
       32, 32, 32, 32, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
       34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
       34, 34, 34, 34, 34

### Binning Mean

In [131]:
def binning_mean(arr,k):
    f = []
    n = 0
    for i in range(len(arr)):
        n = n + arr[i]
        if (i+1)%k == 0:
            r = n/k
            n = 0 
            for j in range(k):
                f.append(r)
    return f

In [142]:
dataEndapan = pd.DataFrame({'Endapan': endapanDf, 'Binning (Mean)':binning_mean(endapanDf,10)})
dataEndapan

Endapan  Binning (Mean)
0         80            80.1
1         80            80.1
2         80            80.1
3         80            80.1
4         80            80.1
..       ...             ...
375      124           123.9
376      124           123.9
377      125           123.9
378      125           123.9
379      125           123.9

[380 rows x 2 columns]

In [144]:
dataTempAir = pd.DataFrame({'Temperature Air': tempAirDf, 'Binning (Mean)':binning_mean(tempAirDf,10)})
dataTempAir

Temperature Air  Binning (Mean)
0                 24            24.0
1                 24            24.0
2                 24            24.0
3                 24            24.0
4                 24            24.0
..               ...             ...
375               41            41.0
376               41            41.0
377               41            41.0
378               41            41.0
379               41            41.0

[380 rows x 2 columns]

In [145]:
dataTempRiver = pd.DataFrame({'Temperature River': tempRiverDf, 'Binning (Mean)':binning_mean(tempRiverDf,10)})
dataTempRiver

Temperature River  Binning (Mean)
0                   15            15.0
1                   15            15.0
2                   15            15.0
3                   15            15.0
4                   15            15.0
..                 ...             ...
375                 25            25.0
376                 25            25.0
377                 25            25.0
378                 25            25.0
379                 25            25.0

[380 rows x 2 columns]

In [158]:
dataSungaiDf = pd.DataFrame({'Binning TDS': binning_mean(endapanDf,10),
                             'Binning Temp Air':binning_mean(tempAirDf,10),
                             'Binning Temp River':binning_mean(tempRiverDf,10)
                            })
dataSungaiDf

Binning TDS  Binning Temp Air  Binning Temp River
0           80.1              24.0                15.0
1           80.1              24.0                15.0
2           80.1              24.0                15.0
3           80.1              24.0                15.0
4           80.1              24.0                15.0
..           ...               ...                 ...
375        123.9              41.0                25.0
376        123.9              41.0                25.0
377        123.9              41.0                25.0
378        123.9              41.0                25.0
379        123.9              41.0                25.0

[380 rows x 3 columns]

## Feature Selection 

## Feature Extraction 